### ISSUE TITLE
[Android Bootcamp] Project 1 - Review my app

### ISSUE THREAD

**Issue by nesquena** [codepath/android-rottentomatoes-demo#2]
My app is complete, please review. Also, I have a question about X, is that the right approach? /cc @codepathreview @codepath

**Comment by dheeru4u** [comment]
My App is completed please review:-  https://github.com/dheeru4u/ThakurTodoApp.git

**Comment by dheeru4u** [comment]
My App is completed please review:- https://github.com/dheeru4u/ThakurTodoApp.git
@codepathreview @codepath

**Comment by wzrthhj** [comment]
My App is completed please review: -ttps://github.com/wzrthhj/SampleToDo.git

@codepathreview @codepath

**Comment by poojavenkatram** [comment]
My App is completed. Please review: https://github.com/poojavenkatram/SimpleListApp 

@codepathreview @codepath

**Comment by nesquena** [comment]
@dheeru4u @wzrthhj @poojavenkatram you want to raise these issues **on your open project repository** not on this one.

**Comment by saeid107** [comment]
My app is complete, please review./cc @codepathreview @codepath

**Comment by nesquena** [comment]
@saeid107 You want to raise an issue on your own project code repo, not here.
